name: Bytestats Go Module
on: [push, pull_request]
jobs:
  test:
    name: Build & Test
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          go env -w GOPRIVATE=github.com/saferwall/multiav
          git config --global url."https://${{ secrets.GITHUB_USER }}:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"
          go version
          go get -u golang.org/x/lint/golint
          make exiftool-install
          make die-install
          make trid-install
          make yara-install
          sudo apt install -qq wamerican

      - name: Build
        run: |
          go build -v ./...

      - name: Test With Coverage
        run: |
          export LC_ALL=C
          go test ./... -race -coverprofile=coverage.out -covermode=atomic

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Run Vet & Lint
        run: |
          go vet .
          golint -set_exit_status=1 .
